version: "3.8"
networks:
  app-network:
    driver: bridge

services:
  #postgres
  database:
    networks:
      - app-network
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    container_name: database
    ports:
      - "127.0.0.1:5432:5432"

  cache:
    networks:
      - app-network
    restart: always
    container_name: cache
    image: redislabs/redismod:latest
    ports:
      - "127.0.0.1:6380:6379"
    environment:
      - REDIS_DB=0

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - cache
    networks:
      - app-network
    container_name: app
    env_file:
      - configs/example.docker.env
    ports:
      - "127.0.0.1:8080:8080"

  migration:
    restart: on-failure
    networks:
      - app-network
    environment:
      - AUTH_MIGRATION_SERVICE_MIGRATIONS_SYSTEM_NAME=auth_migration_service
      - AUTH_MIGRATION_SERVICE_MIGRATIONS_ENV=dev
      - AUTH_MIGRATION_SERVICE_MIGRATIONS_LOG_LEVEL=INFO
      - AUTH_MIGRATION_SERVICE_POSTGRES_URL=postgres://username:password@database:5432/postgres?sslmode=disable
    build:
      context: .
      dockerfile: migrations/Dockerfile
    container_name: migration
    depends_on:
      - database

  jaeger:
    image: jaegertracing/all-in-one:1.51 # At least 1.35 if you want to have enabled collector
    networks:
      - app-network
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports: # Some ports are optional or deprecated, but we still let them be here as it's a general snippet
      - "5775:5775/udp" # agent accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
      - "6831:6831/udp" # agent accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp" # agent accept jaeger.thrift over binary thrift protocol
      - "5778:5778" # agent serve configs
      - "16686:16686" # query serve frontend (Jaeger UI)
      - "14268:14268" # collector accept jaeger.thrift directly from clients
      - "14250:14250" # collector accept model.proto
      - "9411:9411" # collector Zipkin compatible endpoint (optional)
      - "4317:4317" # OTLP collector grpc
      - "4318:4318" # OTLP collector http